location                    = "France Central"
resource_group_name         = "DC-RG"
virtual_network_name        = "DC-VNET"
network_security_group_name = "DC-NSG"
admin_password              = "Lan-main-2009"