variable "location" {}
variable "resource_group_name" {}
variable "DC-VM-NIC-Name" {}
variable "DC-IP-Config-Name" {}
variable "DC-PrivateIP" {}
variable "DC-VM-Name" {}
variable "DC-VM-Size" {}
variable "DC-Computer-Name" {}
variable "DC-VM-localAdmin" {}
variable "DC-VM-localAdmin-PW" {}
variable "DC-NSG-Name" {}
variable "DC-VM-Extension-name" {}
variable "subnet_id" {}
variable "PublicIP_id" {}
variable "Storage_blob" {}
variable "storage_account_name" {}
variable "storage_container_name" {}
variable "script_file_name" {}
